name: Auto-Merge Protect Apps

on:
  workflow_dispatch: 

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge-protect-app:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge protect app PR
        uses: bbq-beets/angel-composite-action@b4b3d0e6735a0e38da83bb6e937c819134c2626f
        with:
          gh-token: ${{ secrets.RETOOL_AUTOMERGE_TOKEN }}
