name: Auto-Merge Protect Apps

on:
  workflow_dispatch: 

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge-protect-app:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge protect app PR
        uses: bbq-beets/angel-composite-action@c4070106255712b942f3d9b245b38cf7812d4e0f
        with:
          gh-token: ${{ secrets.RETOOL_AUTOMERGE_TOKEN }}
