name: Auto-Merge Protect Apps

on:
  workflow_dispatch: 

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge-protect-app:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge protect app PR
        uses: bbq-beets/angel-composite-action@511bda8d31293c26d7aea0ae4d9f2212e2d8846b
        with:
          gh-token: ${{ secrets.RETOOL_AUTOMERGE_TOKEN }}
